App\Entity\Company:
    attributes:
        id:
            groups:
                - 'api:offer:read'
                - 'api:collaborator:read'
        name:
            groups:
                - 'api:offer:read'
                - 'api:collaborator:read'
        presentation: 
            groups:
                - 'api:offer:read'
        logo:
            groups:
                - 'api:offer:read'
