App\Entity\Company:
    attributes:
        id:
            groups:
                - 'api:offer:read'
                - 'api:collaborator:read'
                - 'api:companies:read'
                - 'api:user:read'
        name:
            groups:
                - 'api:offer:read'
                - 'api:offers:read'
                - 'api:collaborator:read'
                - 'api:companies:read'
        presentation: 
            groups:
                - 'api:offer:read'
                - 'api:offers:read'
                - 'api:companies:read'
        city:
            groups:
                - 'api:offer:read'
                - 'api:offers:read'
        logo:
            groups:
                - 'api:offer:read'
        logoIcon:
            groups:
                - 'api:offer:read'
                - 'api:offers:read'
                - 'api:companies:read'
        activities:
            groups:
                - 'api:companies:read'
