App\Entity\Company:
    attributes:
        id:
            groups:
                - 'api:collaborator:read'
        name:
            groups:
                - 'api:collaborator:read'
                - 'api:offer:read'
        decription: 
            groups:
                - 'api:offer:read'
