App\Entity\Skill:
    attributes:
        id:
            groups:
                - 'api:offer:read'
                - 'api:user:read'
        name:
            groups:
                - 'api:offer:read'
                - 'api:user:read'
