App\Entity\Student:
    attributes:
        id:
            groups:
                - 'api:student:read'
        email:
            groups:
                - 'api:student:read'
                - 'api:spontaneousRequest:read'
        roles:
            groups:
                - 'api:student:read'
        phone:
            groups:
                - 'api:student:read'
                - 'api:spontaneousRequest:read'
        gender:
            groups:
                - 'api:student:read'
        firstName:
            groups:
                - 'api:student:read'
                - 'api:spontaneousRequest:read'
        lastName:
            groups:
                - 'api:student:read'
                - 'api:spontaneousRequest:read'
        city:
            groups:
                - 'api:student:read'
                - 'api:spontaneousRequest:read'
                - 'api:user:read'
        postCode:
            groups:
                - 'api:student:read'
                - 'api:user:read'
        address:
            groups:
                - 'api:student:read'
                - 'api:user:read'
        additionalAddress:
            groups:
                - 'api:user:read'
        birthdayAt:
            groups:
                - 'api:student:read'
                - 'api:spontaneousRequest:read'
                - 'api:user:read'
        website: 
            groups:
                - 'api:user:read'
        linkedIn: 
            groups:
                - 'api:user:read'
        driverLicence: 
            groups:
                - 'api:user:read'
        disabled: 
            groups:
                - 'api:user:read'
        school: 
            groups:
                - 'api:user:read'
        diploma: 
            groups:
                - 'api:user:read'
        studyLevel: 
            groups:
                - 'api:user:read'
        formation: 
            groups:
                - 'api:user:read'
        skills: 
            groups:
                - 'api:user:read'
        experiences: 
            groups:
                - 'api:user:read'
        languages: 
            groups:
                - 'api:user:read'


App\Entity\Language:
    attributes:
        id:
            groups:
                - 'api:user:read'
        name:
            groups:
                - 'api:user:read'
        level:
            groups:
                - 'api:user:read'

App\Entity\Experience:
    attributes:
        id:
            groups:
                - 'api:user:read'
        name:
            groups:
                - 'api:user:read'
