name: Php Check

on: [push]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Vendor install
        run: composer install --no-scripts

      - name: Php Lint
        run: make prod-phpcs
      
      - name: PHP Stan
        run: php vendor/bin/phpstan analyse src --level 5
