name: Php Check

on: [push]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          ini-values: memory_limit=-1
          php-version: "8.2"

      - name: Vendor install
        run: composer install --no-scripts

      - name: Php Lint
        run: make pipeline-phpcs
      
      - name: PHP Stan
        run: make pipeline-phpstan
